# Generated by Django 2.1 on 2018-08-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreport',
            name='reportAddedDate',
        ),
        migrations.RemoveField(
            model_name='addreport',
            name='reportCategory',
        ),
        migrations.RemoveField(
            model_name='addreport',
            name='reportCategoryAndCode',
        ),
        migrations.RemoveField(
            model_name='addreport',
            name='reportCode',
        ),
        migrations.RemoveField(
            model_name='addreport',
            name='reportDescription',
        ),
    ]
