# Generated by Django 2.1 on 2018-08-23 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports_page', '0002_auto_20180823_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreport',
            name='reportAddedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addreport',
            name='reportCategory',
            field=models.CharField(default='Annual', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addreport',
            name='reportCategoryAndCode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports_page.addreportCategoryCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addreport',
            name='reportCode',
            field=models.CharField(default='10k', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addreport',
            name='reportDescription',
            field=models.CharField(default='Hello', max_length=30),
            preserve_default=False,
        ),
    ]
