# Generated by Django 2.1 on 2018-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_page', '0003_auto_20180823_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreport',
            name='reportCategory',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='addreport',
            name='reportCode',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
