# Generated by Django 2.1 on 2018-08-26 09:24

from django.db import migrations, models
import reports_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_page', '0005_auto_20180823_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreportcategorycode',
            name='reportCode',
            field=models.CharField(max_length=100, unique=True, validators=[reports_page.models.validate_hyphen]),
        ),
    ]
