# Generated by Django 5.0.2 on 2024-04-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='Year')),
                ('Headline1', models.CharField(max_length=100)),
                ('Description1', models.CharField(max_length=1500)),
                ('Picture1', models.ImageField(help_text='Please Remember to Remove Exif data before uploading, otherwise images might be of incorrect orientation', upload_to='')),
                ('Headline2', models.CharField(max_length=100)),
                ('Description2', models.CharField(max_length=1500)),
                ('Picture2', models.ImageField(help_text='Please Remember to Remove Exif data before uploading, otherwise images might be of incorrect orientation', upload_to='')),
            ],
        ),
    ]
