# Generated by Django 5.0.2 on 2024-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timeline_description3_timeline_description4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='Description1',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='Headline1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='Picture1',
            field=models.ImageField(blank=True, help_text='Please Remember to Remove Exif data before uploading, otherwise images might be of incorrect orientation', null=True, upload_to=''),
        ),
    ]
