# Generated by Django 2.1 on 2018-08-23 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportVersion', models.CharField(choices=[('latest', 'latest')], default='latest', max_length=50, unique=True)),
                ('FCRAreportFile', models.FileField(upload_to='')),
                ('LegalreportFile', models.FileField(upload_to='')),
                ('PlanningCommisionreportFile', models.FileField(upload_to='')),
                ('addedDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
