# Generated by Django 5.0.2 on 2024-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_reports', '0002_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='CSRcertificationletter',
            field=models.FileField(default='default_csr_certification.pdf', upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='MemorandumofAssociation',
            field=models.FileField(default='default_memo_of_association.pdf', upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='PANcardFile',
            field=models.FileField(default='default_PAN_card.pdf', upload_to=''),
        ),
    ]
