# Generated by Django 2.1.1 on 2018-09-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profile_URL',
            new_name='Website_URL',
        ),
    ]
