# Generated by Django 2.1.1 on 2018-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profile_URL',
            new_name='Facebook_URL',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='LinkedIn_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Twitter_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Website_URL',
            field=models.URLField(blank=True),
        ),
    ]
