# Generated by Django 2.1 on 2018-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Picture',
            field=models.ImageField(help_text="If you receive an error on saving Images, Please go back and Re-upload and Try Again. png Images work but jpeg's are recommended", upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_URL',
            field=models.URLField(blank=True),
        ),
    ]
