# Generated by Django 2.1.1 on 2018-09-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180911_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Facebook_URL',
            new_name='Profile_URL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='LinkedIn_URL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Twitter_URL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Website_URL',
        ),
    ]
