# Generated by Django 5.0.2 on 2024-03-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_year_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Social_Media_URL',
            field=models.URLField(blank=True),
        ),
    ]
