# Generated by Django 5.0.2 on 2024-03-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_social_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profile_URL',
            new_name='Social_Media_URL_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Social_Media_URL',
            new_name='Social_Media_URL_2',
        ),
    ]
