# Generated by Django 2.1 on 2018-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, unique=True, verbose_name='year')),
                ('report1', models.FileField(upload_to='')),
                ('reporttitle1', models.CharField(blank=True, max_length=50)),
                ('report2', models.FileField(blank=True, upload_to='')),
                ('reporttitle2', models.CharField(blank=True, max_length=50)),
                ('report3', models.FileField(blank=True, upload_to='')),
                ('reporttitle3', models.CharField(blank=True, max_length=50)),
                ('report4', models.FileField(blank=True, upload_to='')),
                ('reporttitle4', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
