# Generated by Django 2.1 on 2018-08-26 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annualreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='addedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
