# Generated by Django 2.1 on 2018-08-26 07:19

import annualreports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annualreports', '0002_annualreport_addeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='report1',
            field=models.FileField(upload_to='', validators=[annualreports.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='report2',
            field=models.FileField(blank=True, upload_to='', validators=[annualreports.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='report3',
            field=models.FileField(blank=True, upload_to='', validators=[annualreports.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='report4',
            field=models.FileField(blank=True, upload_to='', validators=[annualreports.models.validate_file_extension]),
        ),
    ]
